### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by SirRafaMedina** [eight04/angular-datetime#42]
Hi.

Is there a way to avoid the placeholder?

I tried the following:

`
appModule.config(function(datetimePlaceholder){
    angular.extend(datetimePlaceholder, {
        year: "",
        month: "",
        date: "",
        hour: "",
        minute: ""
    });
});
`

And I got the following error:

`Error: InputMask.digest crashed! Infinite loop on 08:55
    at InputMask.digest (http://localhost/tellware/libs/angular-datetime/custom-input.js:470:27)
    at InputMask.initialize (http://localhost/tellware/libs/angular-datetime/custom-input.js:371:26)
    at new InputMask (http://localhost/tellware/libs/angular-datetime/custom-input.js:226:23)
    at Object.linkFunc [as link] (http://localhost/tellware/libs/angular-datetime/datetime.js:114:14)
    at http://localhost/tellware/Scripts/angular.min.js:16:230
    at ia (http://localhost/tellware/Scripts/angular.min.js:81:35)
    at n (http://localhost/tellware/Scripts/angular.min.js:66:176)
    at g (http://localhost/tellware/Scripts/angular.min.js:58:429)
    at g (http://localhost/tellware/Scripts/angular.min.js:58:446)
    at g (http://localhost/tellware/Scripts/angular.min.js:58:446) <input class="form-control ng-pristine ng-untouched ng-valid" id="fechaMaximo" type="text" name="maximo" ng-class="edited" ng-model="vm.campo.calendario.maximo" ng-pattern="vm.mascarasFecha[vm.campo.calendario.tipo].pattern" placeholder="{{vm.mascarasFecha[vm.campo.calendario.tipo].placeHolder}}" ng-maxlength="vm.mascarasFecha[vm.campo.calendario.tipo].maxLength" datetime="{{vm.mascarasFecha[vm.campo.calendario.tipo].datetime}}">`

**Comment by eight04** [comment]
Currently the parser tests the placeholder first, so an empty placeholder makes it never match.
https://github.com/eight04/custom-input/blob/master/lib/text-parser.js#L24-L29
I'll take a look on it these days.

TBH, I think this directive looks pretty confusing without a placeholder.

**Comment by eight04** [comment]
Fixed in 5.1.0 with custom-input 0.2.0.
