### ISSUE TITLE
IE 11 not supported

### ISSUE THREAD

**Issue by raaaste** [eight04/angular-datetime#64]
I have the element `<input class="ng-pristine ng-valid ng-touched" type="text" ng-model="arvio.paivamaara" ng-disabled="operationInProgress" datetime="dd.MM.yyyy">`, with the model being a date. 
IE 11 displays `Fri Jul 06 2018 12:11:02 GMT+0300 (Suomen kesäaika)`, while Firefox and Chrome both format it as specified in the datetime attribute: `06.07.2018`.

I checked the console and it says something like "TypeError: Object does not support property or function values".

**Comment by eight04** [comment]
I can run the demo on IE11 without problems. Could you provide a demo that generates the error? You can put it on [plunker](https://plnkr.co/).

**Comment by raaaste** [comment]
https://plnkr.co/edit/KkN6vK770qe8ij2eiG9Q This works in Chrome and Firefox, but for some reason IE won't even load the page, probably due to plunker. But I managed to reproduce the error on IE 11 by downloading the plunk and running it locally.
Here's the stack from the console (See translation for the error message above.):

`TypeError: Objekti ei tue ominaisuutta tai menetelmää values
   at m (https://unpkg.com/angular-datetime-input:1:9343)
   at invoke (https://code.angularjs.org/1.4.12/angular.js:4570:7)
   at enforcedReturnValue (https://code.angularjs.org/1.4.12/angular.js:4422:7)
   at invoke (https://code.angularjs.org/1.4.12/angular.js:4570:7)
   at Anonymous function (https://code.angularjs.org/1.4.12/angular.js:4387:13)
   at getService (https://code.angularjs.org/1.4.12/angular.js:4529:11)
   at invoke (https://code.angularjs.org/1.4.12/angular.js:4558:9)
   at Anonymous function (https://code.angularjs.org/1.4.12/angular.js:7369:17)
   at forEach (https://code.angularjs.org/1.4.12/angular.js:341:11)
   at Anonymous function (https://code.angularjs.org/1.4.12/angular.js:7367:13)`

**Comment by eight04** [comment]
[IE doesn't support `Object.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values#Browser_compatibility), so you have to include [babel-polyfill](https://unpkg.com/babel-polyfill@6.23.0/dist/polyfill.js).

Working demo:
https://run.plnkr.co/TLWyBlLuZ5bMNkHb/

I guess we should clarify the polyfill dependency in the readme.

**Comment by raaaste** [comment]
Thanks, I'll try adding it. Demo link doesn't work, though.
